---
- import_tasks: system_setup.yaml

- name: Template kube RPM repo
  template:
    src: kubernetes.repo.j2
    dest: /etc/yum.repos.d/kubernetes.repo

- name: "Install kubectl"
  yum:
    name: "kubectl-1.20.6"
    disable_excludes: kubernetes
    state: present

- name: "Install kubelet"
  yum:
    name: "kubelet-1.20.6"
    disable_excludes: kubernetes
    state: present

- name: "Install kubeadm"
  yum:
    name: "kubeadm-1.20.6"
    disable_excludes: kubernetes
    state: present

- name: "Enable kubelet"
  service:
    name: "kubelet"
    state: started
    enabled: yes

- import_tasks: runtime-cri-o.yaml
